import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import * as C from '../dist/core.js';import {auditContrast} from './contrast-audit.mjs';
const browser=process.env.WEBKIT?await webkit.launch():await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const ctx=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4173');const initial=C.fresh();initial.profile=structuredClone(C.defaults);initial.plan=C.buildPlan(initial.profile,C.wakingDay(initial.profile));await page.evaluate(s=>{localStorage.setItem('afterhours.v1',JSON.stringify(s));localStorage.setItem('afterhours.theme','light');},initial);await page.reload();
const act=(a)=>page.locator(`[data-action="${a}"]`).first();const close=async()=>{if(await page.locator('#modal[open]').count())await page.locator('#modal>.close').click();};
const findings=[];async function inspect(name){await page.waitForTimeout(200);const failures=await auditContrast(page);const sizes=await page.evaluate(()=>[...document.querySelectorAll('dialog[open] button,body:not(:has(dialog[open])) button,dialog[open] .button')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent.trim(),height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width,cls:e.className})).filter(e=>![44,48,64].some(h=>Math.abs(e.height-h)<1)));if(sizes.length)console.log('SIZE',name,JSON.stringify(sizes));findings.push({name,contrast:failures});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375,'overflow '+name);const modal=page.locator('#modal[open]');if(await modal.count()){assert.ok((await modal.boundingBox()).width<=375);const overflow=await modal.evaluate(e=>e.scrollWidth>e.clientWidth+1);assert.equal(overflow,false,'dialog overflow '+name);}assert.deepEqual(failures,[],'contrast '+name);}
const tab=async name=>{await close();await page.locator(`nav a[href="#${name}"]`).click();await inspect(name);};const mealTab=async name=>{await act('meal-tab').count();await page.locator(`[data-tab="${name}"]`).click();await inspect(name);};
for(const theme of ['light','dark']){await page.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.dataset.themePreference=t;localStorage.setItem('afterhours.theme',t);},theme);
 for(const name of ['today','training','meals','progress','settings'])await tab(name);
 await tab('today');await act('habit').click();await inspect(theme+' toast');await page.screenshot({path:`artifacts/round4-${theme}-toast.png`});await page.evaluate(()=>document.querySelector('#toast').classList.remove('show'));
 for(const a of ['checkin','suggesttiming']){await act(a).click();await inspect(a);await close();}
 await tab('training');const trainDay=await page.locator('.week button').evaluateAll(bs=>bs.find(b=>b.querySelector('.train'))?.dataset.day);await page.locator(`[data-day="${trainDay}"]`).click();await act('start').click();await inspect('readiness');if(await act('ready').count())await act('ready').click();await inspect('workout');assert.equal((await page.locator('#modal').boundingBox()).width,375);await act('setdone').click();await inspect('timer');await act('rest-skip').click();await close();
 await tab('meals');for(const name of ['plan','grocery','recipes','ingredients','custom','log'])await mealTab(name);
 await mealTab('plan');for(const a of ['choose-recipes','recommend-menu','swap','editmeal']){if(await act(a).count()){await act(a).click();await inspect(a);await close();}}await mealTab('recipes');await act('recipe').click();await inspect('recipe');await close();
 await act('foodfilters').click();await inspect('food filters');await close();
 await tab('progress');await act('tdee').click();await inspect('tdee');await close();
 await tab('settings');await act('region').click();await inspect('location');await close();for(const id of ['appearance','plan','backup','prices','about']){await page.locator(`[data-action="settings-section"][data-id="${id}"]`).click();await inspect('settings '+id);if(id==='about'){await act('howworks').click();await inspect('sources');await close();await page.locator('[data-action="settings-section"][data-id="about"]').click();await act('delete').click();await inspect('delete confirmation');}await close();}
 await page.locator('[data-action="settings-section"][data-id="plan"]').click();await act('setup').click();await page.locator('#setup-form details').evaluate(e=>e.open=true);await inspect('setup1');const age=page.locator('[name=age]');await age.scrollIntoViewIfNeeded();const ageBox=await age.boundingBox(),foot=await page.locator('.form-foot').boundingBox();assert.ok(ageBox.y+ageBox.height<=foot.y,'Age behind footer');await page.locator('[name=journey]').scrollIntoViewIfNeeded();const journey=await page.locator('[name=journey]').boundingBox();assert.ok(journey.y+journey.height<=foot.y,'XP behind footer');
 for(let n=2;n<=5;n++){await page.getByRole('button',{name:'Continue',exact:false}).click();await inspect('setup'+n);}await page.getByRole('button',{name:'Review my plan'}).click();await inspect('setup6');await close();
}
await tab('meals');await mealTab('ingredients');await act('food-new-ingredient').click();await page.locator('[name=name]').fill('Test oats');await page.locator('[name=pack]').fill('500');await page.locator('[name=price]').fill('5');for(const [k,v]of Object.entries({kcal:200,protein:20,carbs:10,fat:8}))await page.locator(`[name=${k}]`).fill(String(v));await inspect('ingredient editor');await page.getByRole('button',{name:'Save ingredient',exact:true}).click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));const ingredient=Object.keys(saved.customIngredients).find(id=>saved.customIngredients[id].name==='Test oats');assert.ok(ingredient);
await mealTab('custom');await act('food-new-recipe').click();await page.locator('[name=name]').fill('Test bowl');await page.locator('[name=servings]').fill('2');await page.locator('[name=ingredient-0]').selectOption(ingredient);await page.locator('[name=grams-0]').fill('200');await inspect('recipe editor');assert.match(await page.locator('#recipe-live-total').innerText(),/200 kcal.*20 g protein/);await page.getByRole('button',{name:'Save recipe',exact:true}).click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));const recipe=saved.customRecipes.find(r=>r.name==='Test bowl');assert.equal(recipe.items[ingredient],100);
await act('food-log-recipe').click();await inspect('log editor');await page.getByRole('button',{name:'Save food',exact:true}).click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));let entry=saved.foodEntries.find(e=>e.name==='Test bowl');assert.equal(entry.nutrition.kcal,200);assert.equal(entry.nutrition.cost,1);
await mealTab('ingredients');await page.locator(`[data-action=food-edit-ingredient][data-id="${ingredient}"]`).click();await page.locator('[name=price]').fill('10');await page.getByRole('button',{name:'Save ingredient',exact:true}).click();await mealTab('custom');assert.match(await page.locator('.recipe-grid').innerText(),/2\.00/);await mealTab('log');assert.match(await page.locator('.food-log-list').innerText(),/1\.00/);await page.locator(`[data-action=food-edit-entry][data-id="${entry.id}"]`).click();await page.locator('[name=amount]').fill('2');await page.getByRole('button',{name:'Save food',exact:true}).click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));entry=saved.foodEntries.find(e=>e.name==='Test bowl');assert.equal(entry.nutrition.kcal,400);assert.equal(entry.nutrition.cost,4);await act('food-add-entry').click();await page.locator('[name=kind]').selectOption('ingredient');await page.locator('[name=ref]').selectOption(ingredient);await page.locator('[name=amount]').fill('50');await page.getByRole('button',{name:'Save food',exact:true}).click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));const ingredientEntry=saved.foodEntries.find(e=>e.kind==='ingredient');assert.equal(ingredientEntry.nutrition.kcal,100);assert.equal(ingredientEntry.nutrition.cost,1);
await page.locator(`[data-action=food-delete-entry][data-id="${ingredientEntry.id}"]`).click();await act('food-add-entry').click();await page.locator('[name=kind]').selectOption('quick');await page.locator('[name=name]').fill('Cafe lunch');await page.locator('[name=kcal]').fill('500');await page.locator('[name=protein]').fill('30');await page.locator('[name=cost]').fill('12');await page.getByRole('button',{name:'Save food',exact:true}).click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));assert.equal(saved.foodEntries.find(e=>e.name==='Cafe lunch').nutrition.cost,12);
await page.reload();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('afterhours.v1')));assert.equal(saved.foodEntries.find(e=>e.id===entry.id).nutrition.cost,4);assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('artifacts/round4-audit.json',JSON.stringify(findings,null,2));console.log(JSON.stringify({engine:process.env.WEBKIT?'WebKit':'Chromium',views:findings.length,viewport:'375x812',themes:['light','dark'],customIngredientRecipeLog:true,pricePropagation:true,snapshotPreserved:true,errors}));await browser.close();
