import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173');
await page.getByRole('button',{name:/Set up my plan/}).click();
await page.waitForFunction(()=>document.activeElement===document.querySelector('#modal h2'));
assert.equal(await page.locator('#modal h2').evaluate(el=>document.activeElement===el),true);
assert.equal(await page.locator('#modal').evaluate(el=>getComputedStyle(el).overscrollBehavior),'contain');
assert.equal(await page.locator('#modal').evaluate(el=>getComputedStyle(el).height), '812px');
assert.equal(await page.locator('#modal > .close').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)');
await page.getByRole('button',{name:'Close dialog'}).click();
await page.evaluate(async()=>{const C=await import('/core.js');const state=C.fresh();state.profile=structuredClone(C.defaults);state.plan=C.buildPlan(state.profile,C.wakingDay(state.profile));localStorage.setItem('afterhours.v1',JSON.stringify(state));});await page.reload();
await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));const y=await page.evaluate(()=>scrollY);
await page.locator('a[href="#meals"]').first().click();await page.getByRole('button',{name:'Recipe library'}).click();await page.getByRole('button',{name:'Add a recipe'}).click();
await page.waitForFunction(()=>document.activeElement===document.querySelector('#modal h2'));
assert.equal(await page.locator('#modal h2').evaluate(el=>document.activeElement===el),true);
const file='dist/screenshots/training.png';await page.locator('#recipe-photo').setInputFiles(file);
await page.locator('.crop-stage').waitFor();
const crop=await page.locator('.crop-box').evaluate(el=>({left:el.style.left,top:el.style.top,width:el.style.width,height:el.style.height}));
assert.deepEqual(crop,{left:'5%',top:'5%',width:'90%',height:'90%'});
await page.getByRole('button',{name:'Back'}).click();await page.getByRole('button',{name:'Close dialog'}).click();
await page.waitForFunction(()=>document.body.style.position==='');
assert.equal(await page.evaluate(()=>document.body.style.position),'');
await page.setViewportSize({width:812,height:375});await page.setViewportSize({width:375,height:812});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);
console.log(JSON.stringify({focusHeading:true,bodyLockRestored:true,cropDefault:'middle 90%',rotatesWithoutOverflow:true,startScroll:y}));
await browser.close();
