import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});
const page=await context.newPage();
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://localhost:4173',{waitUntil:'domcontentloaded'});
await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});
await page.reload({waitUntil:'domcontentloaded'});
assert.equal(await page.locator('.mobile-pager').count(),1);
const setupScroll=await page.locator('.pager-page[data-page=today]').evaluate(node=>{node.scrollTop=node.scrollHeight;return {top:node.scrollTop,height:node.scrollHeight,client:node.clientHeight}});
assert.ok(setupScroll.height>setupScroll.client&&setupScroll.top>0,JSON.stringify(setupScroll));
await page.locator('.pager-page[data-page=today]').evaluate(node=>node.scrollTop=0);
await page.getByRole('button',{name:/Set up my plan/}).click();
await page.getByRole('button',{name:'Continue'}).click();
assert.equal(await page.locator('#setup-form .daychecks').count(),2);
const dayBoxes=await page.locator('#setup-form .daychecks .check').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect().height));
assert.ok(dayBoxes.every(height=>height===64),JSON.stringify(dayBoxes));
const timeWidths=await page.locator('#setup-form .schedule-grid input[type=time]').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect().width));
assert.ok(timeWidths.length>=4&&Math.max(...timeWidths)-Math.min(...timeWidths)<1,JSON.stringify(timeWidths));
const timeAlignment=await page.locator('#setup-form .schedule-grid input[type=time]').evaluateAll(nodes=>nodes.map(node=>({height:node.getBoundingClientRect().height,lineHeight:getComputedStyle(node).lineHeight,paddingTop:getComputedStyle(node).paddingTop,paddingBottom:getComputedStyle(node).paddingBottom})));
assert.ok(timeAlignment.every(({height,lineHeight,paddingTop,paddingBottom})=>height===48&&lineHeight==='48px'&&paddingTop==='0px'&&paddingBottom==='0px'),JSON.stringify(timeAlignment));
const timeEdges=await page.locator('#setup-form .schedule-grid input[type=time]').evaluateAll(nodes=>nodes.map(node=>{const box=node.getBoundingClientRect();return {left:box.left,right:box.right,width:box.width,viewport:innerWidth};}));
assert.ok(timeEdges.every(box=>box.left>=0&&box.right<=box.viewport&&box.width<=box.viewport-32),JSON.stringify(timeEdges));
await page.getByRole('button',{name:'Continue'}).click();
assert.equal(await page.locator('#setup-form input[name=weights][type=checkbox]').count(),26);
await page.locator('#setup-form input[name=dumbbell]').check();
await page.locator('#setup-form .weight-picker summary').click();
await page.locator('#setup-form input[name=weights][value="5"]').check();
await page.locator('#setup-form input[name=weights][value="10"]').check();
await page.getByRole('button',{name:'Continue'}).click();
assert.ok(await page.locator('#setup-form .food-picker input[type=checkbox]').count()>30);
await page.locator('#setup-form .food-picker summary').click();
await page.locator('#setup-form input[name=allergies][value="milk"]').check();
await page.locator('#setup-form input[name=avoidFoods][value="beef"]').check();
await page.getByRole('button',{name:'Continue'}).click();
await page.getByRole('button',{name:'Review my plan'}).click();
await page.getByRole('button',{name:'Save plan'}).click();
await page.waitForTimeout(150);
await page.evaluate(()=>{const saved=JSON.parse(localStorage.getItem('afterhours.v1'));saved.profile.sleep='11:00';localStorage.setItem('afterhours.v1',JSON.stringify(saved));});
await page.reload({waitUntil:'domcontentloaded'});await page.waitForTimeout(120);
assert.equal(await page.getByText('Sleep by 11:00 am',{exact:true}).count(),1);
const drag=async(selector,from,to,duration=160)=>page.locator(selector).first().evaluate((node,{from,to,duration})=>{
  const touch=(x,y)=>({identifier:1,target:node,clientX:x,clientY:y,pageX:x,pageY:y,screenX:x,screenY:y});
  const fire=(type,touches,changedTouches,cancelable=false)=>{const event=new Event(type,{bubbles:true,cancelable});Object.defineProperties(event,{touches:{value:touches},changedTouches:{value:changedTouches}});node.dispatchEvent(event);};
  fire('touchstart',[touch(...from)],[touch(...from)]);
  fire('touchmove',[touch(...to)],[touch(...to)],true);
  const start=performance.now();while(performance.now()-start<duration){}
  fire('touchend',[],[touch(...to)]);
},{from,to,duration});
assert.equal(await page.evaluate(()=>getComputedStyle(document.body).fontFamily),'Archivo, sans-serif');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);
assert.equal(await page.locator('.pager-page[data-page=today] img').count(),0);
const assertPage=async name=>{
  await page.waitForTimeout(300);
  assert.equal(page.url().split('#')[1],name);
  assert.equal(await page.locator('nav a.active').getAttribute('href'),`#${name}`);
  assert.equal(await page.locator('.mobile-pager').evaluate(node=>node.style.getPropertyValue('--page-drag')),'');
};
const views=['today','training','meals','progress','settings'];
for(let cycle=0;cycle<2;cycle++){
  await drag('.pager-page[data-page=today]',[330,300],[80,305]);
  await assertPage('training');
  for(const name of views.slice(2)){
    const current=views[views.indexOf(name)-1],selector=current==='training'?'.pager-page[data-page=training] [data-action=demo]':`.pager-page[data-page=${current}]`;
    await drag(selector,[330,300],[80,305]);
    await assertPage(name);
  }
  for(const name of [...views].reverse().slice(1)){
    const current=views[views.indexOf(name)+1];
    const selector=current==='training'?'.pager-page[data-page=training] [data-action=demo]':`.pager-page[data-page=${current}]`;
    await drag(selector,[45,300],[300,305]);
    await assertPage(name);
  }
}
await drag('.pager-page[data-page=today]',[330,300],[80,305]);
await assertPage('training');
await drag('.pager-page[data-page=training]',[200,250],[205,500]);
await page.waitForTimeout(100);
assert.equal(page.url().split('#')[1],'training');
await page.locator('nav a[href="#meals"]').click();await page.waitForTimeout(300);
assert.equal(page.url().split('#')[1],'meals');
assert.equal(await page.locator('.pager-page[data-page=meals] img').count(),0);
assert.ok(await page.locator('.pager-page[data-page=meals] button').count()<108);
assert.equal(await page.getByText('Within budget',{exact:true}).count(),0);
const suggestionLayout=await page.locator('.pager-page[data-page=meals] .meal-suggestions .recipe-photo-card').first().evaluate(node=>{const card=node.getBoundingClientRect(),title=node.querySelector('strong').getBoundingClientRect(),copy=getComputedStyle(node.querySelector('.recipe-photo-copy'));return {cardLeft:card.left,titleLeft:title.left,textAlign:copy.textAlign,justify:copy.justifyContent};});
assert.ok(suggestionLayout.titleLeft-suggestionLayout.cardLeft<=24,JSON.stringify(suggestionLayout));
assert.equal(suggestionLayout.textAlign,'left');
assert.equal(await page.locator('.pager-page[data-page=meals] .tabs').evaluate(node=>getComputedStyle(node).display),'grid');
await page.locator('.pager-page[data-page=meals] [data-action=meal-tab][data-tab=grocery]').tap();
assert.equal(await page.locator('.pager-page[data-page=meals] [data-action=meal-tab][data-tab=grocery]').getAttribute('aria-pressed'),'true');
await page.locator('.pager-page[data-page=meals] [data-action=meal-tab][data-tab=plan]').tap();
assert.equal(await page.locator('.pager-page[data-page=meals] [data-action=meal-tab][data-tab=plan]').getAttribute('aria-pressed'),'true');
const plannedCard=page.locator('.pager-page[data-page=meals] .meal-day[open] .menu-card').first();
const plannedLayout=await plannedCard.evaluate(node=>{const recipe=node.querySelector('.recipe-photo-card').getBoundingClientRect(),actions=node.querySelector('.meal-card-actions').getBoundingClientRect();return {recipeWidth:recipe.width,left:recipe.left,actionsRight:actions.right,viewport:innerWidth};});
assert.ok(plannedLayout.recipeWidth>=150,JSON.stringify(plannedLayout));
assert.ok(plannedLayout.left>=0&&plannedLayout.actionsRight<=plannedLayout.viewport,JSON.stringify(plannedLayout));
const mealSummary=page.locator('.pager-page[data-page=meals] .meal-day').first().locator('summary');
assert.equal(await mealSummary.locator('svg').count(),1);
assert.equal(await mealSummary.evaluate(node=>getComputedStyle(node,'::after').content),'none');
await page.locator('.pager-page[data-page=meals] [data-action=meal-tab][data-tab=recipes]').click();
assert.ok(await page.locator('.pager-page[data-page=meals] .recipe-photo-card').count()>0);
assert.equal(await page.locator('.pager-page[data-page=meals] img').count(),0);
await page.locator('.pager-page[data-page=meals] .recipe-photo-card').first().click();
assert.equal(await page.locator('#modal .recipe-hero img').count(),0);
assert.equal(await page.locator('#modal [data-action=copyrecipe]').count(),0);
assert.equal(await page.locator('#modal>.close').evaluate(node=>getComputedStyle(node).opacity),'0');
assert.equal(await page.locator('#modal>.close').getAttribute('aria-label'),'Close');
await page.locator('#modal [data-action=recipe-tab][data-tab=method]').click();
assert.ok(await page.locator('#modal .steps li').count()>=5);
await page.goBack();await page.waitForTimeout(100);assert.equal(await page.locator('#modal').getAttribute('open'),null);
await page.locator('nav a[href="#progress"]').click();await page.waitForTimeout(280);
await page.locator('.pager-page[data-page=progress] [data-action=tdee]').click();
const sheet=page.locator('#modal');assert.ok(await sheet.isVisible());
await sheet.evaluate(node=>node.scrollTop=node.scrollHeight);
const pull=page.locator('#modal .sheet-pull-zone');assert.ok(await pull.isVisible());
assert.equal(await pull.evaluate(node=>getComputedStyle(node).position),'static');
const sheetBox=await sheet.boundingBox();assert.ok(sheetBox.y+sheetBox.height<=804.5,JSON.stringify(sheetBox));
const pullBox=await pull.boundingBox();assert.ok(pullBox.height<=52&&pullBox.y+pullBox.height<=804.5,JSON.stringify(pullBox));
const pullStart={x:pullBox.x+pullBox.width/2,y:pullBox.y+18};
await page.mouse.move(pullStart.x,pullStart.y);await page.mouse.down();await page.mouse.move(pullStart.x,pullStart.y+60,{steps:4});
const far=await sheet.evaluate(node=>node.style.getPropertyValue('--sheet-drag'));
await page.mouse.move(pullStart.x,pullStart.y+30,{steps:3});
const returned=await sheet.evaluate(node=>node.style.getPropertyValue('--sheet-drag'));await page.mouse.up();
assert.deepEqual({far,returned},{far:'60px',returned:'30px'});await page.waitForTimeout(300);assert.ok(await sheet.isVisible());
const pointerDrag=async(selector,dy)=>{const box=await page.locator(selector).boundingBox(),x=box.x+box.width/2,y=box.y+18;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y+dy,{steps:5});await page.mouse.up();};
await pointerDrag('#modal .sheet-pull-zone',35);await page.waitForTimeout(300);assert.ok(await sheet.isVisible());
await pointerDrag('#modal .sheet-pull-zone',-60);await page.waitForTimeout(300);assert.ok(await sheet.isVisible());
await pointerDrag('#modal #tdee-result',100);await page.waitForTimeout(300);assert.ok(await sheet.isVisible());
await pointerDrag('#modal .sheet-pull-zone',60);await page.waitForTimeout(280);assert.equal(await sheet.getAttribute('open'),null);
await page.locator('.pager-page[data-page=progress] [data-action=tdee]').click();
await sheet.evaluate(node=>node.scrollTop=node.scrollHeight);
await pointerDrag('#modal .sheet-pull-zone',60);await page.waitForTimeout(280);assert.equal(await sheet.getAttribute('open'),null);
await page.locator('nav a[href="#today"]').click();await page.waitForTimeout(280);
for(let index=0,count=await page.locator('.pager-page[data-page=today] .week button').count();index<count&&!await page.locator('.pager-page[data-page=today] [data-action=start]').count();index++)await page.locator('.pager-page[data-page=today] .week button').nth(index).click();
await page.locator('.pager-page[data-page=today] [data-action=start]').click();await page.locator('[data-action=ready]').click();
assert.match(await page.locator('#modal .session-top').innerText(),/1 of/);
await drag('#modal .workout-exercise h2',[320,180],[50,185],180);await page.waitForTimeout(120);
assert.match(await page.locator('#modal .session-top').innerText(),/2 of/);
await page.keyboard.press('Escape');
assert.equal(errors.length,0,errors.join('\n'));
await browser.close();
console.log(JSON.stringify({viewport:'375x812',pager:true,sheets:true,photoFree:true,errors}));
